{% set name = "forest" %}
{% set version = "0.20.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: aaa78d148e8bc9c9ae113ea1b2960826d6967dbb5093c35a8c6ce9e8193c886c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - nodejs >=10.13
  host:
    - python
    - pip
  run:
    - python
    - iris <3
    - bokeh
    - datashader
    - xarray
    - dataclasses  # [py36]
    - geojson
    - pyyaml
    - netCDF4
    - scipy
    - cftime
    - pandas
    - pygrib
    - intake
    - intake-esm
    - h5netcdf
    - typer

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
