{% set name = "forest" %}
{% set version = "0.20.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: 58e0693c2bc9fb73bc5a55c2186fb6403d6cd284d1a2f5adda434a9dfc051216

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - forest = forest.cli.alternative:app

requirements:
  build:
    - nodejs >=10.13
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - iris <3
    - bokeh
    - datashader
    - xarray
    - dataclasses
    - geojson
    - pyyaml
    - netCDF4
    - scipy
    - cftime
    - pandas
    - pygrib
    - intake
    - intake-esm
    - h5netcdf
    - typer

test:
  imports:
    - forest
  commands:
    - forest --help

about:
  home: http://github.com/informatics-lab/forest
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
