{% set name = "forest" %}
{% set version = "0.20.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: c44c8d03884c931cca771deee3b9e42d9b13e773e8f4293bd90c92180fe94e1a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - nodejs >=10.13
  host:
    - python
    - pip
  run:
    - python
    - iris <3
    - bokeh
    - datashader
    - xarray
    - dataclasses  # [py36]
    - geojson
    - pyyaml
    - netCDF4
    - scipy
    - cftime
    - pandas
    - pygrib
    - intake
    - intake-esm
    - h5netcdf

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
