{% set name = "forest" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: b78a8090368c945869715b9c09643cfc70147ae66eedfcab2cb7b31fe6b7f319

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - nodejs >=10.13
  host:
    - python
    - pip
  run:
    - python
    - iris
    - bokeh >=2.0.2
    - datashader
    - xarray
    - dataclasses  # [py36]
    - geojson

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
