{% set name = "forest" %}
{% set version = "0.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: fea306e389fb0b832bd41c6abcdeee785d4847dddce4ba76c40eb463d68296ed

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - nodejs >=10.13
  host:
    - python
    - pip
  run:
    - python
    - iris
    - bokeh >=2.0.2
    - datashader
    - xarray
    - dataclasses  # [py36]
    - geojson

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
